name = "cf-usage-checker"
main = "index.js"
compatibility_date = "2024-10-01"

[vars]
CF_EMAIL = "your@email.com"
CF_API_KEY = "your-global-api-key"
CF_API_TOKEN = "your-api-token"     # 推荐
CF_ACCOUNT_ID = "your-account-id"   # 可选