name = "cf-usage-checker"
main = "index.js"
compatibility_date = "2024-10-01"

[vars]
MULTI_CF_API_TOKENS = "token1,token2,token3..."
TELEGRAM_BOT_TOKEN = "你的_Telegram_Bot_Token"
TELEGRAM_CHAT_ID = "你的_Telegram_Chat_ID"